#pragma once

#define KVM_DEVICE 0x8000

/*
* ioctls for kvm
*/
#define KVM_GET_API_VERSION		CTL_CODE(KVM_DEVICE,0x800,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_CREATE_VM			CTL_CODE(KVM_DEVICE,0x801,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_CHECK_EXTENSION		CTL_CODE(KVM_DEVICE,0x802,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_GET_VCPU_MMPA_SIZE	CTL_CODE(KVM_DEVICE,0x803,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_TRACE_ENABLE		CTL_CODE(KVM_DEVICE,0x804,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_TRACE_PAUSE			CTL_CODE(KVM_DEVICE,0x805,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_TRACE_DISABLE		CTL_CODE(KVM_DEVICE,0x806,METHOD_BUFFERED,FILE_ANY_ACCESS)