#pragma once

#define KVM_DEVICE 0x8000

/*
* ioctls for kvm
*/
#define KVM_GET_API_VERSION				CTL_CODE(KVM_DEVICE,0x800,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_CREATE_VM					CTL_CODE(KVM_DEVICE,0x801,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_CHECK_EXTENSION				CTL_CODE(KVM_DEVICE,0x802,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_GET_VCPU_MMPA_SIZE			CTL_CODE(KVM_DEVICE,0x803,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_TRACE_ENABLE				CTL_CODE(KVM_DEVICE,0x804,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_TRACE_PAUSE					CTL_CODE(KVM_DEVICE,0x805,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_TRACE_DISABLE				CTL_CODE(KVM_DEVICE,0x806,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_GET_MSR_FEATURE_INDEX_LIST	CTL_CODE(KVM_DEVICE,0x807,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_SET_USER_MEMORY_REGION		CTL_CODE(KVM_DEVICE,0x808,METHOD_BUFFERED,FILE_ANY_ACCESS)

/*
* ioctls for vcpu
*/
#define KVM_CREATE_VCPU		CTL_CODE(KVM_DEVICE,0x809,METHOD_BUFFERED,FILE_ANY_ACCESS)
#define KVM_RUN				CTL_CODE(KVM_DEVICE,0x80A,METHOD_BUFFERED,FILE_ANY_ACCESS)